### PR TITLE
Remove notification categories

### PR DESCRIPTION
**Pull request by shahnami**
Merge after https://github.com/OpenZeppelin/defender/pull/5554
https://linear.app/openzeppelin-development/issue/PLAT-4229/remove-notification-categories-from-sdk

### CODE REVIEW

**Review by MCarlomagno — APPROVED** [review]
LGTM

**Review by zeljkoX — APPROVED** [review]
LGTM

Question: If user had assigned some category what will happen after we remove them?

**Comment by shahnami** [comment]
> LGTM
> 
> 
> 
> Question: If user had assigned some category what will happen after we remove them?

I have a migration script to handle those cases. We need to run that before deployment. We will look at all categories associated to a monitor and assign the notifications directly to the monitor.

**Review by MCarlomagno — APPROVED** [review]
LGTM

**Pull request merged**
