### PR TITLE
feat: Add support for kvstore client

### PR DESCRIPTION
**Pull request by MCarlomagno**
# Summary
Adds kvstore package to be used in actions and for local development
https://linear.app/openzeppelin-development/issue/PLAT-2065/add-support-for-kvstore-client-in-platform-sdk

## Checklist

- [x] Add a reference to related issues in the PR description.
- [x] Add unit tests if applicable.

### CODE REVIEW

**Review by shahnami — APPROVED** [review]
Lgtm!

**Review by zeljkoX — APPROVED** [review]
LGTM

Thanks!

**Comment by MCarlomagno** [comment]
@socketsecurity ignore all

**Comment by MCarlomagno** [comment]
https://github.com/SocketSecurity ignore-all

**Comment by MCarlomagno** [comment]
@socketsecurity ignore-all

**Pull request merged**
